const quotes = [
  "Believe in yourself.",
  "Stay curious.",
  "Consistency beats talent.",
  "Dream big, start small.",
  "Progress over perfection.",
  "Keep moving forward.",
  "Focus on what matters.",
  "Small steps every day.",
  "Make it happen.",
  "Do it with purpose.",

  "Learn something new daily.",
  "Discipline creates freedom.",
  "Trust the process.",
  "Work hard, stay humble.",
  "Growth begins outside comfort.",
  "Be better than yesterday.",
  "Turn ideas into action.",
  "Stay patient and persistent.",
  "Success loves preparation.",
  "Think long term.",

  "Failure is feedback.",
  "Action beats overthinking.",
  "Create more, consume less.",
  "Your future needs you.",
  "Stay consistent.",
  "Build before you boast.",
  "Focus fuels success.",
  "Start now.",
  "Keep improving.",
  "Learn by doing.",

  "Stay hungry.",
  "Embrace challenges.",
  "Your mindset matters.",
  "Results take time.",
  "Never stop learning.",
  "Execution is everything.",
  "Effort compounds.",
  "Progress is progress.",
  "Be intentional.",
  "Stay disciplined.",

  "Turn setbacks into setups.",
  "Clarity creates confidence.",
  "Hard work pays off.",
  "Build useful things.",
  "Solve real problems.",
  "Skills over shortcuts.",
  "Stay focused.",
  "One step at a time.",
  "Adapt and overcome.",
  "Keep building.",

  "Confidence comes from practice.",
  "Do the hard things.",
  "Stay optimistic.",
  "Learn. Build. Repeat.",
  "Quality over quantity.",
  "Stay committed.",
  "Push your limits.",
  "Discomfort leads to growth.",
  "Stay curious, stay sharp.",
  "Make progress daily.",

  "Think clearly.",
  "Move with purpose.",
  "Growth is a choice.",
  "Stay resilient.",
  "Build momentum.",
  "Focus on solutions.",
  "Create your path.",
  "Trust yourself.",
  "Keep going.",
  "Never quit.",

  "Time rewards consistency.",
  "Be your own competition.",
  "Stay adaptable.",
  "Work with intention.",
  "Progress is earned.",
  "Learning never stops.",
  "Focus and execute.",
  "Build habits, not hacks.",
  "Stay motivated.",
  "Finish strong.",
];
module.exports = quotes;
